# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'durgesh-coder-ust'
    scannerMode: 'MSBuild'
    projectKey: 'Durgesh-coder-ust'
    projectName: 'dotnetcoreDocker'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.sln'
    feedsToUse: 'select'
- task: VSBuild@1
  inputs:
    solution: '**\*.sln'
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: CmdLine@2
  inputs:
    script: 'dir'

- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(System.DefaultWorkingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '2b66a97f-4183-47b0-92f1-2de112bfa22b'
    vstsFeedPackage: 'f3caa9c6-53a4-4d13-b575-03c3a7c2af36'
    vstsPackageVersion: '19.7.363'
- task: CmdLine@2
  inputs:
    script: |
      sudo mv $(System.DefaultWorkingDirectory)/twistcli /usr/bin/twistcli
      sudo chmod +x /usr/bin/twistcli